### ISSUE TITLE
AVG Antivirus for Mac Error

### ISSUE THREAD

**Issue by henri** [synack/knockknock#23]
On a fresh 10.10.2 if you install AVG Antivirus for Mac <http://www.avg.com/au-en/avg-antivirus-for-mac>, running knockknock will report the following error : 

    ERROR: 
     EXCEPTION, knocknock() threw: [Errno 2] No such file or directory: '/Applications/AVG'
    Traceback (most recent call last):
      File "knockknock.py", line 61, in knocknock
        results = scan(args.plugin)
      File "knockknock.py", line 417, in scan
        pluginResults = plugin.plugin_object.scan()
      File "/Users/smc/Desktop/knockknock-master/plugins/unclassified.py", line 85, in scan
        results['items'].append(file.File(path))
      File "/Users/smc/Desktop/knockknock-master/file.py", line 63, in __init__
        self.size = os.path.getsize(self.path)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 49, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 2] No such file or directory: '/Applications/AVG'

**Comment by patrickwardle** [comment]
Thanks for you feedback! Just pushed a fix for this this :) Can you let me know if this fixes the issue for you?

**Comment by patrickwardle** [comment]
fixed

**Comment by henri** [comment]
Seems to work great. Thanks!
